version: '3'
services:
  postgres:
    image: public.ecr.aws/docker/library/postgres:16
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgres/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
  express:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./dist:/app/dist